name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up timestamp
      id: timestamp
      run: echo "::set-output name=time::$(date +%s)"

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ github.repository }}:test-${{ steps.timestamp.outputs.time }}
